### ISSUE TITLE
Typo in post about essential data science

### ISSUE THREAD

**Issue by maskypy40** [jessecambon/jessecambon.github.io#8]
Hi Jesse,

I was reading your post "Data science essentials" and trying it for myself.
However, I got an error when I tried:
`mpg3 <- mpg %>% slice(1,44:45) %>%
  select(displ,year)`
The error indicated that slice takes 1 argument when using %>%.
I think it should be:
`mpg3 <- mpg %>% slice(c(1,44:45)) %>%
  select(displ,year)`

**Comment by jessecambon** [comment]
That's interesting, the code was all run in RMarkdown to generate the document so it should work. Try updating your dplyr package and seeing if you get the same error : `install.packages("dplyr")`

**Comment by maskypy40** [comment]
In my setting, we cannot directly install packages. I have tidyverse 1.2.1 and dplyr 0.7.8 installed. Maybe these somewhat older versions are the cause?

**Comment by maskypy40** [comment]
Hmm, the dataset world_bank_pop also doesn't show up. I conclude that it is a version-thing on my side.
